FROM python:latest

MAINTAINER Daria Kutkanych "d.goubenko@gmail.com"

COPY . /lesson3

WORKDIR /lesson3
	
RUN python -m pip install --upgrade pip
RUN pip install pipenv && pipenv install --dev --system --deploy


ENTRYPOINT ["python"]
CMD ["main.py"]