"""'Init'

Revision ID: b60d21f3a4c6
Revises: 919f93e47da4
Create Date: 2022-07-06 15:12:22.917811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60d21f3a4c6'
down_revision = '919f93e47da4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'addressbook', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'book_id')
    # ### end Alembic commands ###
